# Ansible playbook AWS - install docker (2021)
---
- name: "AWS - Install docker"
  hosts: awsec2instances
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras
        - git

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker packages from amazon-linux-extras packages
      shell: "amazon-linux-extras install docker -y"

    - name: Enable Some packages from amazon-linux-extras packages
      shell: "amazon-linux-extras enable python3.8 ansible2 docker"
    
    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3.8
        - ansible

    - name: Enable docker service
      shell: sudo usermod -a -G docker ec2-user

    - name: Downloading docker-compose
      shell: sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose  

    - name: Asing docker-compose privileges
      shell: chmod +x /usr/local/bin/docker-compose

    - name: clean yum metadata cache
      command: yum clean metadata
      args:
        warn: false

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Upgrade pip3
      shell: "python3.8 -m pip install pip --upgrade"

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
        executable: /usr/local/bin/pip3.8
      vars:
        packages:
        - boto
        - boto3
        - requests
        - docker
        - docker-compose